### ISSUE TITLE
Project Gallery

### ISSUE THREAD

**Issue by dhanishgajjar** [ahmadawais/brandfie#2]
Image 2, for reason is not loading. Tried replacing the image a few times.

**Comment by ahmadawais** [comment]
The link you have added is http://brandfie.pro/img/brandfie/works/2.jpg and there is no image there.

**Comment by ahmadawais** [comment]
You need to deploy again. The build folder doesn't have that image. Push the entire code to master first and then deploy.

**Comment by dhanishgajjar** [comment]
Case sensitive, JPG extension, renamed it.

**Comment by ahmadawais** [comment]
YUP!
