### ISSUE TITLE
Lightbox Options

### ISSUE THREAD

**Issue by dhanishgajjar** [ahmadawais/brandfie#3]
Have implemented Lightbox on project gallery. Options code is in the main.js file, however the options are not working.

**Comment by ahmadawais** [comment]
What options? Be more elaborate. What did you add and isn't working?

**Comment by dhanishgajjar** [comment]
I have put options in the main.js file for the Lightbox2 plugin / package installed in bower components.

https://github.com/ahmadawais/brandfie/blob/master/src/js/main.js

Documentation of Lightbox2 are here http://lokeshdhakar.com/projects/lightbox2/#options

**Comment by ahmadawais** [comment]
Can you share the exact lines? You know you can click on a line and then press shift and click on another to highlight the lines on GitHub

**Comment by ahmadawais** [comment]
What did you change here? https://github.com/ahmadawais/brandfie/blob/master/src/js/main.js#L5-L13

**Comment by ahmadawais** [comment]
What is expected behavior and not the outcome?

**Comment by dhanishgajjar** [comment]
If you click on the project photos, the first photo zooms and displays itself properly. Expected behaviour. But the images after that, are abrupt, I was thinking these settings that are mentioned in the documentation, might help control the behaviour.

**Comment by ahmadawais** [comment]
Nops, at my end all of them are same and working just fine :)

**Comment by dhanishgajjar** [comment]
Can close this for now then, will come back to it later.

**Comment by ahmadawais** [comment]
Take a look! http://recordit.co/0Te6z3K57v
