### ISSUE TITLE
Titles enhancement 

### ISSUE THREAD

**Issue by mohamedFalah** [ahmadawais/brandfie#6]
I took a look at the website and I think it has some typo. also, I think changing some words and paraphrasing it would be better and Some letters, if it was capital, would be better also.

For example, in contact: 
What was written 
Ask a Question --------------- Our Contacts
my changes would be 
Questions? Ask Us  ------------ Contact Us

Clarification: 
in (Ask a Question), I think it is like indicating to the user to ask only one question.
in (Our Contacts), there is only one contact way was written. Not sure if there other but it would be better to change it.

in my changes, you have consistency in the two sentences. In addition, implying to the user to ask as many questions as he wants. simple and informative.

can I commit this change and the other few changes?

**Comment by ahmadawais** [comment]
@mohamedFalah it is clearly stated that this is a work in progress. I appreciate you taking a look at it, but we have not finalized anything yet :) Once it is complete from our end, we'd love to have more input from you.
